name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Deploy Streamlit app
      uses: streamlit/streamlit-app-action@v0.0.3
      with:
        app-path: app.py
    - name: Deploy to GitHub Pages
      run: |
        streamlit run app.py --server.headless true &
        mkdir -p ~/.streamlit/
        echo "\
        [server]\n\
        headless = true\n\
        enableCORS=false\n\
        port = 8501\n\
        " > ~/.streamlit/config.toml
        streamlit run app.py &

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./  # Specify the directory to publish